version: '3.1'
services:
  demohello:
    image: nginxdemos/hello
    restart: always
    ports:
      - 80:80
  guthubactions:
    image: bee7ch/githubactions:0.1.6
    restart: always
    ports:
      - 8080:80