apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: guthubactions
  name: guthubactions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: guthubactions
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: guthubactions
    spec:
      containers:
        - image: bee7ch/githubactions:0.1.6
          name: guthubactions
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
